### PR TITLE
Cron testing

### PR DESCRIPTION
**Pull request by mkasenberg**

### CODE REVIEW

**Comment by codecoup-tester** [comment]
Scheduled PR, https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2045260749, estimated start time: 19:31:08, test case count: 459, estimated duration: 7:19:51

**Comment by codecoup-tester** [comment]
Scheduled PR, https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2045260749, estimated start time: 19:57:54, test case count: 459, estimated duration: 7:19:51

**Comment by codecoup-tester** [comment]
Scheduled PR, https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2045260749, estimated start time: 09:38:32, test case count: 459, estimated duration: 7:19:51

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr AICS -e AICS/SR/SGGIT AICS/SR/SPN

**Comment by codecoup-tester** [comment]
Scheduled PR, https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2046959678, estimated start time: 11:01:40, test case count: 6, estimated duration: 0:03:12

**Comment by codecoup-tester** [comment]
Scheduled PR, https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2046959678, estimated start time: 11:10:14, test case count: 6, estimated duration: 0:03:12

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>AICS    AICS/SR/CP/BV-01-C              PASS<br>AICS    AICS/SR/CP/BV-02-C              PASS<br>AICS    AICS/SR/CP/BV-03-C              PASS<br>AICS    AICS/SR/CP/BV-04-C              PASS<br>AICS    AICS/SR/CP/BV-05-C              PASS<br>AICS    AICS/SR/SPE/BI-01-C             PASS</details>

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr AICS/SR/CP/BV-01-C DIS/SR/SGGIT/CHA/BV-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2126753607, board: nrf52, estimated start time: 12:41:12

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2126753607, board: nrf52, estimated start time: 12:58:32

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2126753607, board: nrf52, estimated start time: 13:06:55

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2126753607, board: nrf52, estimated start time: 13:18:59

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2126753607, board: nrf53, estimated start time: 13:19:00

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Reason unknown

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Reason unknown

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2126753607, board: nrf52, estimated start time: 13:38:50

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2126753607, board: nrf53, estimated start time: 13:38:51

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Reason unknown

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2126753607, board: nrf52, estimated start time: 13:55:22

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2126753607, board: nrf53, estimated start time: 13:55:23

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>DIS     DIS/SR/SGGIT/CHA/BV-01-C        PASS</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>AICS    AICS/SR/CP/BV-01-C              PASS</details>

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2259826662, board: nrf52, estimated start time: 10:56:37, test case count: 12, estimated duration: 0<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C<br>GAP/ADV/BV-01-C<br>GAP/ADV/BV-02-C<br>GAP/ADV/BV-03-C<br>GATT/CL/GAC/BV-01-C<br>GATT/CL/GAD/BV-01-C<br>GATT/CL/GAD/BV-02-C<br>L2CAP/COS/CFC/BV-01-C<br>L2CAP/COS/CFC/BV-02-C<br>L2CAP/COS/CFC/BV-03-C</details>

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/mkasenberg/auto-pts/pull/6#issuecomment-2259826662, board: nrf52, estimated start time: 11:05:16, test case count: 12, estimated duration: 0<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C<br>GAP/ADV/BV-01-C<br>GAP/ADV/BV-02-C<br>GAP/ADV/BV-03-C<br>GATT/CL/GAC/BV-01-C<br>GATT/CL/GAD/BV-01-C<br>GATT/CL/GAD/BV-02-C<br>L2CAP/COS/CFC/BV-01-C<br>L2CAP/COS/CFC/BV-02-C<br>L2CAP/COS/CFC/BV-03-C</details>

**Pull request closed without merging**
